name: release

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  tarball:
    if: github.event_name == 'push'
    timeout-minutes: 1
    runs-on: ubuntu-latest
    env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # https://github.community/t/how-to-get-just-the-tag-name/16241/4
      - name: Extract the version number
        id: get_version
        run: |
          echo ::set-output name=V::$(python abnosql/version.py)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          . venv/bin/activate
          pip install twine wheel

      - name: Build and upload tarball to PyPI
        run: |
          . venv/bin/activate
          python setup.py sdist
          twine upload dist/abnosql-${{ steps.get_version.outputs.V }}.tar.gz

      - name: Build and upload wheel to PyPI
        run: |
          . venv/bin/activate
          python setup.py bdist_wheel
          twine upload dist/abnosql-${{ steps.get_version.outputs.V }}-py3-none-any.whl